### ISSUE TITLE
Nothing is happening...

### ISSUE THREAD

**Issue by Apyre83** [Sedorikku1949/Game_Of_Life#1]
As the README mentions, once the project is cloned, you just have to open the html file into your navigator, none in particular, hence i used Firefox 115.0 on Ubuntu 22.04.2 LTS, and nothing is actually happening.
I can press any of the 3 buttons, or click anywhere on the site but still nothing...
I also get the message on the top left "No game initialized"

**Comment by lynn2910** [comment]
Hello,
Thanks for reporting the issue, the problem was that the JavaScript files were not present when I published the code on github.

I've updated the repository, and everything works fine now 😅

**Comment by Apyre83** [comment]
Works fine now !
